# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  desc "You will need to run the example app once in iPhone 5s simulator to allow the Photos library access."
  lane :test do
    test_it
  end

  lane :test_it do
    scan(
      destination: "platform=iOS Simulator,name=iPhone 6,OS=9.3",
      clean: true
    )
  end

  desc "Publish to Cocoapods"
  lane :pod do
    ensure_git_status_clean
    ensure_git_branch
    ensure_pod_trunk_session
    test_it
    version = version_bump_podspec
    pod_lib_lint
    git_commit(
      path: "./DLFPhotosPicker.podspec",
      message: "bump podspec version")
    add_git_tag(
      tag: version
    )
    push_to_git_remote
    pod_push
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
