# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.97.2"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."


  end

  desc "Runs all the tests"
  desc "You will need to run the example app once in iPhone 5s simulator to allow the Photos library access."
  lane :test do
    test_it
  end

  lane :test_it do
    reset_simulators
    simulatorId = Helper.backticks('xcrun instruments -s | grep -o "iPhone 6 (9.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/"').strip!
    sh "set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme PhotosPicker -project ../PhotosPicker.xcodeproj -destination 'platform=iOS Simulator,id="+simulatorId+"' clean build test | xcpretty "
    simulatorId = Helper.backticks('xcrun instruments -s | grep -o "iPhone 5s (9.3) \[.*\]" | grep -o "\[.*\]" | sed "s/^\[\(.*\)\]$/\1/"').strip!
    sh "set -o pipefail && env NSUnbufferedIO=YES xcodebuild -scheme PhotosPickerUITest -project ../PhotosPicker.xcodeproj -destination 'platform=iOS Simulator,id="+simulatorId+"' clean build test | xcpretty "
  end

  lane :demo do
    sh "cd .. && set -o pipefail && xcodebuild -scheme PhotosPicker -project PhotosPicker.xcodeproj -configuration 'Debug' -sdk 'iphonesimulator9.3' -destination 'platform=iOS Simulator,name=iPhone 6' CONFIGURATION_BUILD_DIR=build  build | tee /Users/nico/Library/Logs/gym/PhotosPicker-PhotosPicker.log | xcpretty"
    sh "cd ../build && zip -r PhotosPicker.app.zip  PhotosPicker.app"
    sh "cd .. && blackbox_edit_start appetizerkey"
    appetizertoken = Helper.backticks('cat ../appetizerkey').strip!
    appetize(
      path: './build/PhotosPicker.app.zip',
      api_token: appetizertoken, # get it from https://appetize.io/docs#request-api-token
      public_key: 'rkaxakuky73h73gvjre9fa9kkc' # get it from https://appetize.io/dashboard
    )
  end

  desc "Publish to Cocoapods"
  lane :pod do
    ensure_git_status_clean
    ensure_git_branch
    ensure_pod_trunk_session
    test_it
    version = version_bump_podspec
    pod_lib_lint
    git_commit(
      path: "./DLFPhotosPicker.podspec",
      message: "bump podspec version")
    add_git_tag(
      tag: version
    )
    push_to_git_remote
    pod_push
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
